# Generated by Django 4.0.6 on 2022-07-09 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0af1f004-85da-42fa-9898-db1c2efe3ad3'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'db_table': 'article',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ee0c532b-7174-4a63-aeef-28be36f1be52'), editable=False, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=30, unique=True, verbose_name='ジャンル名')),
            ],
        ),
    ]
