# Generated by Django 4.0.6 on 2022-07-09 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('eec2296a-ca9e-4b02-88c9-b8db2a7bcc1f'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'db_table': 'article',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f8401d7d-fd6e-4e95-a6af-d0fd531fef47'), editable=False, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=30, unique=True, verbose_name='ジャンル名')),
                ('articel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.articles', verbose_name='記事')),
            ],
            options={
                'verbose_name': 'ジャンル',
                'verbose_name_plural': 'ジャンル',
                'db_table': 'genre',
                'ordering': ['id'],
            },
        ),
    ]
