# Generated by Django 4.0.6 on 2022-07-09 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'verbose_name': 'ジャンル', 'verbose_name_plural': 'ジャンル'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2aad0a29-56bf-4554-8511-963f33e68349'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.UUID('929f78f8-602e-489d-901f-9a062523b773'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
    ]
